### ISSUE TITLE
paymentType не приходит в запросе checkOrder

### ISSUE THREAD

**Issue by harabchuk** [yandex-money/yandex-money-kit-django#3]
Коллеги, 
при запросе checkOrder от Яндекс не приходит поле paymentType . Из-за этого не проходит валидацию форма BasePaymentForm. Пришлось поле paymentType сделать не обязательным. Хотя в [документациии](https://money.yandex.ru/doc.xml?id=526537) в п.4.2.1 это поле описано.
Подскажите, я делаю что-то не так?

**Comment by amureki** [comment]
@harabchuk на прошлой неделе возникала эта проблема, как я понял, ошибка была со стороны Яндекса. Сейчас все поправили, думаю, можно закрывать.
