### ISSUE TITLE
paymentPayerCode - обязательное поле ?

### ISSUE THREAD

**Issue by lavr** [yandex-money/yandex-money-kit-django#9]
В тестовой среде при оплате тестовой кредитной картой в ручку check не передаётся paymentPayerCode. Поскольку поле в форме forms.CheckForm отмечено как обязательное, form.is_valid возвращает False и ручка check в итоге возвращает ошибку.

[Документация](https://tech.yandex.ru/money/doc/payment-solution/payment-notifications/payment-notifications-check-docpage/) не даёт прямого ответа на вопрос, должен ли сервер всегда присылать это поле.
Но из документации мы узнаём, что paymentPayerCode это "номер счета в Яндекс.Деньгах, с которого производится оплата", а это даёт основания предполагать, что при оплате кредитной картой сервер имеет некоторые основания не передавать это поле.

Кажется, что можно смело сделать paymentPayerCode необязательным (required=False) полем в forms.NoticeForm и forms.CheckForm

**Comment by osado** [comment]
Да, не передаётся, точнее не так давно перестал передаваться, я делал pull request https://github.com/yandex-money/yandex-money-kit-django/pull/8 так всё работает
